### ISSUE TITLE
 Translation Progress (Batch #1) - Finished

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-pt-BR#1]
## --------------------- ! UPDATE IMPORTANTE ! ------------------
Todos os arquivos já foram designados, futuramente abriremos novos para tradução!

### Revisores Oficiais
- @jessescn
- @rafaeelaudibert 
- @Dennissiq 
- @jay-jlm 
- @iaurg
- @mjr 
- @abnersajr 

## Para os novos tradutores

Siga os passos descritos no nosso [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md). **Daremos um limite de 2 SEMANAS para que cada tradução seja finalizada, no intuito de manter a tradução sempre dinâmica.**

## Labels

* [] :running_man: - Em Progresso
* [] :eyes: - Sob Revisão
* [] :heavy_check_mark: - Feita!

## Páginas

Aqui estão listadas as páginas que foram traduzidas, estão em processo de tradução ou estão disponíveis para serem traduzidas. Você pode conferir os estados delas verificando as suas `labels`.  

### Community
    
* [x] community/code-of-conduct (@jessescn) :heavy_check_mark: #5 

### Tutorial

* [x] tutorial/index (@iaurg) :heavy_check_mark: #11
* [x] tutorial/part-zero (@Dennissiq) :heavy_check_mark: #4
* [x] tutorial/part-one (@jpedroschmitz) ✔️  #89 
* [x] tutorial/part-two (@crisgon) ✔️  #121  
* [x] tutorial/part-three (@gutofoletto) :heavy_check_mark:  #27 
* [x] tutorial/part-four (@renanmav) ✔️  #14 
* [x] tutorial/part-five (@luizcieslak) :heavy_check_mark:  #34 
* [x] tutorial/part-six (@gabrielferreiraa) :heavy_check_mark:  #56 
* [x] tutorial/part-seven (@ArthurFerrao) ✔️  #55 
* [x] tutorial/part-eight (@gabrielreisn) :heavy_check_mark:  #35 
    

### Docs

* [x] docs/index (@iaurg) :heavy_check_mark: #11 
* [x] docs/quick-start (@gvarandas) :heavy_check_mark:  #38 
* [x] docs/recipes (@LucasRuy) :heavy_check_mark:  #40 
* [x] docs/glossary (@mjr) :heavy_check_mark: #17 
* [x] docs/gatsby-cli (@jay-jlm) :heavy_check_mark: #7

**Comment by gvarandas** [comment]
I can tackle the quick start section.

**Comment by jessescn** [comment]
Of course @gvarandas, thanks :)

**Comment by Italox** [comment]
Oh nice! Can I take the tutorial section?

**Comment by brunoxd13** [comment]
I can take the  docs/index, can be?

**Comment by Dennissiq** [comment]
Hey guys! I caught the style guide section. ok?

**Comment by Dennissiq** [comment]
Of course @brunoxd13 :)

**Comment by Italox** [comment]
Of course @brunoxd13, if you have any issue post here or join us on Discord https://discord.gg/v3Fg3x

**Comment by jay-jlm** [comment]
@jessescn  Olá pessoal, gostaria de ajudar na pagina da CLI . (docs/gatsby-cli.md)

**Comment by jessescn** [comment]
Show de bola @jay-jlm, toda sua :)

**Comment by tesseralis** [comment]
@jessescn I think we're going to remove the gatsby style guide from the list of core docs. Looking at it more it seems like it's mostly stuff that's relevant for english speakers (english grammar rules and information on writing new docs).

I think a more valuable thing would be to update this repo's [style guide](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/style-guide.md), by referencing the english version.

**Comment by jessescn** [comment]
@tesseralis makes sense, i will do this

**Comment by Dennissiq** [comment]
Pessoal, como o style guide não será mais traduzido, eu peguei o **tutorial/part-zero** para fazer!

**Comment by jay-jlm** [comment]
@tesseralis  Are  there guidelines/best pratices for managing branches in a translation repo? Or should the PRs target the master branch directly?

**Comment by tesseralis** [comment]
@jay-jlm PRs should target the master branch

**Comment by jpedroschmitz** [comment]
Hey guys 👋 
I can take the `tutorial/part-one` page to translate!

**Comment by Italox** [comment]
@jpedroschmitz, it's yours! if you have any issue post here or in Discord. :brazil:

**Comment by renanmav** [comment]
Can I take the tutorial/part-four section?

**Comment by luizcieslak** [comment]
Can I take the tutorial/part-five section?

**Comment by Italox** [comment]
@renanmav, of course! If you have any issue post here or on Discord. :brazil:

**Comment by Italox** [comment]
@luizcieslak It's yours! :brazil:

**Comment by crisgon** [comment]
Can I take the `tutorial/part-two` ?

**Comment by Dennissiq** [comment]
Of course @crisgon :)

**Comment by Italox** [comment]
Welcome @crisgon

**Comment by gabrielferreiraa** [comment]
Can I take the `tutorial/part-six`?

**Comment by ArthurFerrao** [comment]
Can I take the tutorial/part-seven?

**Comment by jessescn** [comment]
@gabrielferreiraa , @gutofoletto and @ArthurFerrao, of course! feel free sending any questions in our discord channel and make sure to check out the Contributing.md to know more about the translation process.

**Comment by mjr** [comment]
Can i translate `docs/glossary`?

**Comment by Italox** [comment]
Welcome @mjr!

**Comment by gabrielferreiraa** [comment]
@Italox edit the issue with @gabrielferreiraa @gutofoletto  e @ArthurFerrao :)

**Comment by gabrielreisn** [comment]
Can i take `tutorial/part-eight` ?

**Comment by Italox** [comment]
@gabrielferreiraa Oh! I forgotten. Edited. Welcome @gabrielferreiraa @gutofoletto e @ArthurFerrao :) - Join us on [Discord](https://discordapp.com/invite/v3Fg3x)

**Comment by Italox** [comment]
@gabrielreisn Welcome!

**Comment by LucasRuy** [comment]
E ai pessoal, tudo bem?

Gostaria de contribuir. Posso ajudar de alguma forma?

**Comment by Italox** [comment]
@LucasRuy , tudo certo e você Lucas? Pode sim, temos uma última página precisando de alguem para traduzi-la `docs/recipes`, se tiver interesse podemos designa-la à você.

**Comment by jessescn** [comment]
Olá @lucasmoura-dev, esses arquivos listados são os principais. Pretendemos abrir novos arquivos em breve para tradução, vamos apenas alguns arquivos serem aceitos para não sobrecarregar a revisão e prezar pela qualidade, mas quando novos arquivos forem abertos podemos lhe adicionar :).

**Comment by rjcjunior** [comment]
Olá, também gostaria de ajudar. Poderia me adicionar quando surgir novos arquivos?

**Comment by lucasmoura-dev** [comment]
O convite do Discord não está funcionando, talvez está expirado.

**Comment by Italox** [comment]
Link Discord updated: [Join us](https://discord.gg/6r9SP9)

**Comment by LucasRuy** [comment]
@Italox , opa tenho interesse em ajudar na página `docs/recipes`. Podemos deixar combinado comigo contribuindo com a tradução dela então?

**Comment by jessescn** [comment]
@LucasRuy pode começar os trabalhos, toda sua!

**Comment by jessescn** [comment]
@mjr uma vez que o `docs/glossary`, proponho que quebremos o arquivo em dois, para que duas pessoas possam fazer ao mesmo tempo. Isso diminuiria o peso pra ti e agilizaria o trabalho, uma vez que esse arquivo é bastante importante para as outras traduções. O que achas?

**Comment by LucasRuy** [comment]
@jessescn fechou!

**Comment by jay-jlm** [comment]
@jessescn Poderia atualizar o estado da minha para "em revisao"? Obrigado!

**Comment by jessescn** [comment]
Avisando aqui que quem quiser contribuir e não conseguiu uma tradução, acabei de abrir uma issue nova com uma leva de arquivos a serem traduzidos :tada:

**Comment by mjr** [comment]
@jessescn acho que pode ser, se ficar melhor assim, sem problemas... 👍😁

> @mjr uma vez que o `docs/glossary`, proponho que quebremos o arquivo em dois, para que duas pessoas possam fazer ao mesmo tempo. Isso diminuiria o peso pra ti e agilizaria o trabalho, uma vez que esse arquivo é bastante importante para as outras traduções. O que achas?

**Comment by Sphinxs** [comment]
Existe alguma parte a ser traduzida?

**Comment by jessescn** [comment]
Tem sim @Sphinxs, da uma olhada na outra issue aberta que tem uma lista cheia de novos arquivos para tradução :)

**Comment by Italox** [comment]
Pessoal que quiser contribuir com as traduções: Nesta issue já foram requisitados todos as páginas. Temos mais páginas para tradução [nesta nova issue](https://github.com/gatsbyjs/gatsby-pt-BR/issues/9), mesmo padrão, acessa issue > escolhe sua página > comenta > traduz. Qualquer dúvida estamos ai!

**Comment by Italox** [comment]
Boa noite pessoal.

Descobri uma coisa legal para dar uma animada nas traduções:

Quem contribui (faz pull) em projetos Gatsby pode solicitar brindes gratuitos [loja do Gatsby](https://store.gatsbyjs.org/)

[Veja as regras e como proceder](https://www.gatsbyjs.org/contributing/contributor-swag/)

**Comment by LucasRuy** [comment]
> Boa noite pessoal.
> 
> Descobri uma coisa legal para dar uma animada nas traduções:
> 
> Quem contribui (faz pull) em projetos Gatsby pode solicitar brindes gratuitos na [loja do Gatsby](https://store.gatsbyjs.org/)
> 
> [Veja as regras e como proceder](https://www.gatsbyjs.org/contributing/contributor-swag/)

O louco, da hora demais!

**Comment by rafaeelaudibert** [comment]
Olá @jpedroschmitz e @crisgon! Alguma novidade para conseguir fazer a tradução dos arquivos assigned pra vocês?

Se vocês estiverem sem tempo acho que seria legal liberar esses dois arquivos pra outras pessoas traduzirem, já que eles são extremamente importantes pro projeto, já que são de tutoriais, ainda mais dos primeiros tutoriais. O que vocês me dizem?

**Comment by jpedroschmitz** [comment]
Opa @rafaeelaudibert, desculpa a demora para terminar e enviar a tradução. Eu já iniciei ela e em breve devo terminar, apenas acabei adiando devido a uns eventos e faculdade. Peço desculpas pela demora!

**Comment by rafaeelaudibert** [comment]
Imagina @jpedroschmitz, não precisa se apressar de maneira alguma, é apenas pra checar se você ainda está interessado na tradução. Assim que tiver ela pronta, vamos ficar muito felizes em mandar ela pro live. Obrigado desde já! Bons eventos/provas/trabalhos! 🥇

**Comment by jpedroschmitz** [comment]
Fala @rafaeelaudibert, passando para avisar que terminei a tradução e já abri uma [PR](https://github.com/gatsbyjs/gatsby-pt-BR/pull/89). Qualquer probleminha que tiver é só me dar um toque lá para eu fazer as alterações necessárias 💜

**Comment by crisgon** [comment]
@rafaeelaudibert , estava na correria e não consegui terminar. Hoje eu finalizo e mando PR.

**Comment by jessescn** [comment]
@crisgon alguma novidade?

**Comment by crisgon** [comment]
@jessescn , desculpa a demora, de verdade. Não consegui terminar tudo de uma vez e tive que ir fazendo aos poucos, mas já acabei e mandei o PR.
