### ISSUE TITLE
Corrigindo arquivos - URGENTE

### ISSUE THREAD

**Issue by jessescn** [gatsbyjs/gatsby-pt-BR#235]
Com a resolução de conflitos vindo do repositório principal, alguns arquivos necessitam ter partes re-traduzidas. Com o intuito de acelerar o processo, eu estou abrindo essa issue para este propósito.

Fique livre para requisitar de 1-5 arquivos de uma vez (já que muitos possuem apenas poucas partes para traduzir.

**Caso queira ajudar, é só comentar na issue qual(s) arquivo(s) você tem interesse em traduzir** 

Obs: Revisores podem editar essa issue direto.

#### tutorial/

* [x] part-zero/index.md ✔️  (@iaurg) #240
* [x] part-one/index.md ✔️  (@iaurg) #240
* [x] part-eight/index.md ✔️  (@iaurg) #240

#### contributing/

* [x] blog-and-website-contributions.md :heavy_check_mark: (@luizeboli) #250
* [x] code-contributions.md ✔️ (@henry-ns) #245
* [x] docs-contributions.md ✔️ (@borelbruno) #257 
* [x] how-to-open-a-pull-request.md ✔️ (@iaurg) #262
* [x] managing-pull-requests.md ✔️ (@iaurg) #262
* [x] organize-a-gatsby-event.md :heavy_check_mark: (@henry-ns) #247
* [x] pair-programming.md ✔️ (@iaurg) #262
* [x] setting-up-your-local-dev-environment.md :heavy_check_mark: (@afucher) #256 

#### Docs/

* [x] themes/using-a-gatsby-theme.md :heavy_check_mark: (@lancaluis) #258 
* [x] building-an-e-commerce-site.md ✔️ (@MatheusGoncalvs) #255 
* [x] gatsby-cli.md :heavy_check_mark: (@afucher) #249
* [x] gatsby-on-linux.md :heavy_check_mark: (@felipefbs) #238
* [x] gatsby-on-windows.md :heavy_check_mark: (@felipefbs) #239
* [x] glossary.md :heavy_check_mark: (@felipefbs) #253 
* [x] making-your-site-accessible.md :heavy_check_mark: (@MatheusGoncalvs) #263 
* [x] plugins.md :heavy_check_mark: (@JuanVieiraPrado) #246 
* [x] porting-to-gatsby.md ✔️ (@luizeboli) #261 
* [x] recipes.md :heavy_check_mark:  (@IsaqueIgor) #242
* [x] routing.md ✔️ (@luizeboli) #251
* [x] static-folder.md ✔️ (@felipefbs) #254 
* [x] styled-components.md ✔️  (@henry-ns) #236
* [x] tailwind-css.md ✔️ (@henry-ns) #236
* [x] what-is-a-plugin.md :heavy_check_mark:  (@henry-ns) #237
* [x] what-you-dont-need-plugins-for.md :heavy_check_mark:  (@henry-ns) #237
* [x] winning-over-clients.md :heavy_check_mark:   (@IsaqueIgor) #242

**Comment by felipefbs** [comment]
Posso pegar os arquivos  `gatsby-on-linux.md` `gatsby-on-windows.md`?

**Comment by jessescn** [comment]
Opa @felipefbs, pode sim

**Comment by felipefbs** [comment]
Feita a tradução do arquivo gatsby-on-linux.md  https://github.com/gatsbyjs/gatsby-pt-BR/pull/238
vou trabalhar agora no outro arquivo :)

**Comment by lancaluis** [comment]
Opa! Gostaria de ajudar na tradução das docs, pensei em começar com o arquivo **themes/using-a-gatsby-theme.md** tem como?

**Comment by henry-ns** [comment]
Está sim @lancaluis :) pode com começar

**Comment by IsaqueIgor** [comment]
Hey! Adoraria contribuir com as traducoes, Esta liberado para pegar o **recipes.md** e winning-over-clients.md?

**Comment by jessescn** [comment]
fique a vontade @IsaqueIgor, se tiver alguma dúvida sobre o processo de contribuição, recomendo ler o arquivo [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md) :)

**Comment by luizeboli** [comment]
Sup! 

Gostaria de traduzir o arquivo **blog-and-website-contributions.md**, posso?

**Comment by henry-ns** [comment]
claro @luizeboli, é seu :)

**Comment by JuanVieiraPrado** [comment]
Olá, estou começando minha carreira de e eu gostaria de ajudar na tradução das docs, eu poderia traduzir o arquivo plugins.md para poder entender como funciona e adquirir conhecimento?

**Comment by henry-ns** [comment]
Marcado para você @JuanVieiraPrado :D

Qualquer dúvida sobre o processo de contribuição, recomendo ler o arquivo [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md)

**Comment by iaurg** [comment]
Olá pessoal,

Peguei mais três arquivos para traduzir:
contributing/how-to-open-a-pull-request.md
contributing/managing-pull-requests.md
contributing/pair-programming.md

**Comment by afucher** [comment]
vou traduzir o `gatsby-cli.md`

**Comment by borelbruno** [comment]
Posso pegar para tradução o  `vou traduzir o gatsby-cli.md`?

**Comment by borelbruno** [comment]
Posso pegar para tradução o `docs-contributions.md`?

**Comment by henry-ns** [comment]
Marcado para vocês @afucher e @borelbruno :)

**Comment by henry-ns** [comment]
@luizeboli, pode fazer como está lá e separar em 2

**Comment by afucher** [comment]
@henry-ns abri o PR pro `gatsby-cli` #249 
Posso já pegar outro? Se sim, pode ser o `setting-up-your-local-dev-environment.md`

**Comment by henry-ns** [comment]
marquei para você @afucher

**Comment by luizeboli** [comment]
Mandei a PR #250 para o arquivo **blog-and-website-contributions.md**.

Posso pegar o arquivo **routing.md**?

**Comment by felipefbs** [comment]
routing.md e static-folder.md estão livres?

**Comment by henry-ns** [comment]
@luizeboli, pode sim, marquei para você.

**Comment by henry-ns** [comment]
@felipefbs, o @luizeboli pediu primeiro o `routing.md`mas, o `static-folder.md` está livre.

**Comment by felipefbs** [comment]
> @felipefbs, o @luizeboli pediu primeiro o `routing.md`mas, o `static-folder.md` está livre.

Então me passa o  glossary.md

**Comment by iaurg** [comment]
Está marcado para você o  glossary.md @felipefbs, qualquer dúvida é só avisar.

**Comment by MatheusGoncalvs** [comment]
Quero pegar esses dois: building-an-e-commerce-site.md e making-your-site-accessible.md. O que vocês acham?

**Comment by henry-ns** [comment]
Pode ser @MatheusGoncalvs! Marquei para você :tada:
 
Temos apenas um arquivo disponível agora, que é o `porting-to-gatsby.md`.

**Comment by luizeboli** [comment]
@henry-ns pode marcar pra mim?

**Comment by afucher** [comment]
Abri o PR para `setting-up-your-local-dev-environment.md`
Posso pegar: `porting-to-gatsby.md`? Acredito que é o último.

**Comment by henry-ns** [comment]
Posso sim, @luizeboli! Marcado!
