### ISSUE TITLE
Translation Progress (Batch #2) - Finished

### ISSUE THREAD

**Issue by jessescn** [gatsbyjs/gatsby-pt-BR#9]
# Batch 2

### Revisores Oficiais
- @jessescn
- @rafaeelaudibert 
- @Dennissiq 
- @jay-jlm 
- @iaurg
- @mjr 
- @abnersajr 

## Para os novos tradutores

Siga os passos descritos no nosso [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md). **Daremos um limite de 2 SEMANAS para que cada tradução seja finalizada, no intuito de manter a tradução sempre dinâmica.**

## Páginas

Aqui estão listadas as páginas que foram traduzidas, estão em processo de tradução ou estão disponíveis para serem traduzidas da pasta `contributing/`. Você pode conferir os estados delas verificando as suas `labels`.  

## Labels

* :running_man: - Em Progresso
* :eyes: - Sob Revisão
* :heavy_check_mark: - Feita!

### Paginas `contributing/`

* [x] blog-and-website-contributions (@abnersajr) :heavy_check_mark: #13 
* [x] code-contributions (@jessescn) :heavy_check_mark:  #26  
* [x] community-contributions (@vsmjr) :heavy_check_mark: #142  
* [x] community (@mauriciomutte) ✔️  #25   
* [x] contributor-swag (@rafaeelaudibert) :heavy_check_mark: #18 
* [x] docs-contributions (@abnersajr) :heavy_check_mark:  #22 
* [x] gatsby-governance-model (@peaonunes) :heavy_check_mark:  #19 
* [x] how-to-contribute (@Dennissiq) :heavy_check_mark: #16   
* [x] how-to-file-an-issue (@emilioheinz) ✔️ #15 
* [x] how-to-label-an-issue (@thaisquintana) ✔️ #41 
* [x] how-to-make-an-reproducible-test-case (@peaonunes) ✔️  #30 
* [x] how-to-open-a-pull-request (@guilhermepiovesan) :heavy_check_mark:  #29 
* [x] how-to-pitch-gatsby (@peaonunes ) :heavy_check_mark:  #209
* [x] how-to-run-a-gatsby-workshop (@thiagorowof) :heavy_check_mark:  #42  
* [x] how-to-write-a-stub (@iaurg) ✔️ #62
* [x] managing-pull-requests (@drd-2rcl) :heavy_check_mark:  #54  
* [x] organize-a-gatsby-event (@vsmjr) ✔️ #52 
* [x] pair-programming (@abnersajr) :heavy_check_mark:  #24 
* [x] rfc-process (@helloncanella) ✔️ #60  
* [x] setting-up-your-local-dev-environment (@fmoliveira) ✔️  #44  
* [x] site-showcase-submissions (@gutofoletto) ✔️ #53 
* [x] submit-to-creator-showcase (@luizcieslak) ✔️  #33 
* [x] submit-to-plugin-library (@Rahmon) ✔️  #45 
* [x] submit-to-starter-library (@Dennissiq) ✔️  #37  
* [x] triaging-github-issues (@vinifarias) :heavy_check_mark: #32  
* [x] using-an-online-dev-environment (@emilioheinz) :heavy_check_mark:  #39 
* [x] where-to-participate (@vsmjr) ✔️ #199  
* [x] why-contribute-to-gatsby (@lucas-mdiniz) ✔️  #51

**Comment by lucas-mdiniz** [comment]
Can I take why-contribute-to-gatsby?

**Comment by jessescn** [comment]
Of Course! before you start translating, be sure to read the [contributing.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md). Any question feel free to send it in [our discord](https://discordapp.com/invite/6r9SP9)!

**Comment by mauriciomutte** [comment]
Can I take _community_?

**Comment by jessescn** [comment]
@mauriciomutte all yours! remember to read the contributing :)

**Comment by rafaeelaudibert** [comment]
I'm taking (and auto assigning me hehe) /contributor-swag. :)

**Comment by emilioheinz** [comment]
I would like to translate the `how-to-file-an-issue` file ;)

**Comment by jessescn** [comment]
@emilioheinz  Sure!

**Comment by abnersajr** [comment]
Please, @jessescn tag me on that one `blog-and-website-contributions`

**Comment by jessescn** [comment]
@abnersajr as you wish :), @abnersajr and @emilioheinz  remember both of you to read the contributing and enter the Discord channel If you have some questions!

**Comment by emilioheinz** [comment]
Yes @jessescn , I'll do it!!

**Comment by thiagorowof** [comment]
Can i take `how-to-run-a-gatsby-workshop` ??
(can i get more than one?)

**Comment by leandrogrillo** [comment]
can i get `how-to-pitch-gatsby`? :D

**Comment by jessescn** [comment]
of course @leandrogrillo ! feel free to send any questions in our discord channel, and make sure to read the contributing.md :smile:.

**Comment by Dennissiq** [comment]
Hey guys! I'll take the `how-to-contribute`, ok?

**Comment by jessescn** [comment]
@Dennissiq go ahead man :running_man:

**Comment by cassule** [comment]
Hey guys! I would like to translate the community-contributions file.

**Comment by emilioheinz** [comment]
There is a PR open to the `how-to-file-an-issue` file, I would like to start the `using-an-online-dev-environment` file.

**Comment by rafaeelaudibert** [comment]
@cassule and @emilioheinz, they're all yours! :sparkles:

**Comment by fmoliveira** [comment]
Can I take `setting-up-your-local-dev-environment`?

**Comment by vsmjr** [comment]
Can I take _organize-a-gatsby-event_?

**Comment by peaonunes** [comment]
Fiz a tradução de `gatsby-governance-model`, pois era apenas um esboço.
Gostaria de fazer a tradução de `how-to-label-an-issue`, mas tenho algumas dúvidas, especialmente em traduzir `issue` e `label` já que o Github em si não as traduz. O link do convite do discord tá expirado :( !

**Comment by jessescn** [comment]
Olá @peaonunes, você pode conferir traduções como essa acessando o link do google sheets presente no contributing.md. Quando nós mergamos sua PR eu coloco seu nome na próxima tradução :smile:

**Comment by jessescn** [comment]
Link novo para o [discord](https://discord.gg/xJWpW9U).

**Comment by jessescn** [comment]
@peaonunes eu vi que você não havia pedido a tradução antes, eu vou deixar passar dessa vez :roll_eyes:, mas na próxima lembre de ler o contributing como é aconselhado.

**Comment by peaonunes** [comment]
Opa @jessescn , joia. Passou batido o google sheets hehe. Acho que o google sheets poderia ficar fechado para edição, ta para qualquer um com link poder editar 😅

**Comment by jessescn** [comment]
A gente deixou aberto exatamente para a galera poder contribuir uma vez que ainda estamos debatendo alguns dos termos

**Comment by thiagorowof** [comment]
> @thiagorowof If you didnt got any file yet, i can give that file to you :)

Of course! Put it to me!
I will start as soon as possible.

**Comment by Rahmon** [comment]
Could I take submit-to-plugin-library?

**Comment by thaisquintana** [comment]
Can I take the how-to-label-an-issue? :)

**Comment by Dennissiq** [comment]
Of course @thaisquintana :)

**Comment by fmoliveira** [comment]
Hello! Can I start translating `setting-up-your-local-dev-environment`?

**Comment by jessescn** [comment]
All yours @fmoliveira!! remember to read our [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md) and any questions feel confortable to send in our [Discord channel](https://discordapp.com/invite/xJWpW9U).

**Comment by abnersajr** [comment]
I'm taking `pair-programming`

**Comment by drd-2rcl** [comment]
I would like to get this issue `managing-pull-requests`

**Comment by abnersajr** [comment]
@drd-2rcl go ahead with `managing-pull-requests`. Remember to read our CONTRIBUTING.md and any questions feel comfortable to send in our Discord channel.

**Comment by jessescn** [comment]
@abnersajr tente não pegar outra tradução antes de uma delas ser mergada, isso sobrecarrega nossas traduções :disappointed: .

**Comment by peaonunes** [comment]
Gostaria de traduzir `how-to-make-a-reproducible-test-case` 😄

**Comment by Italox** [comment]
Boa noite pessoal.

Descobri uma coisa legal para dar uma animada nas traduções:

Quem contribui (faz pull) em projetos Gatsby pode solicitar brindes gratuitos na [loja do Gatsby](https://store.gatsbyjs.org/)

[Veja as regras e como proceder](https://www.gatsbyjs.org/contributing/contributor-swag/)

**Comment by Italox** [comment]
@peaonunes Welcome! If you had any issue post here or on Discord

**Comment by guilhermepiovesan** [comment]
Can I take `how-to-open-a-pull-request`?

**Comment by Italox** [comment]
@guilhermepiovesan Of course! Welcome :brazil:

**Comment by Italox** [comment]
Can I take `how-to-write-a-stub` ?

**Comment by jessescn** [comment]
Pode sim @Italox, ainda não entendi o porque do povo ficar pedindo em inglês, mas beleza kkk

**Comment by helloncanella** [comment]
Oi @jessescn , pode me linkar ao `rfc-process`

**Comment by helloncanella** [comment]
Oi @jessescn , pode me linkar ao rfc-process.

**Comment by jessescn** [comment]
Claro @helloncanella, lembra de dar uma olhada no nosso contributing, lá tem umas informações legais que podem te ajudar na tradução 😄

**Comment by luizcieslak** [comment]
@jessescn posso pegar a `submit-to-creator-showcase`?

**Comment by Italox** [comment]
@jessescn Normalmente a galera interage em inglês no github, mas não sei se aqui tem sentido mesmo auheuaheuhae.

@luizcieslak É seu!

**Comment by Dennissiq** [comment]
Hello guys! I'll take the `submit-to-starter-library`, ok?

**Comment by gutofoletto** [comment]
Can I help with site-showcase-submissions?

**Comment by abnersajr** [comment]
@gutofoletto go ahead with `site-showcase-submissions`. Remember to read our CONTRIBUTING.md and any questions feel comfortable to send in our Discord channel.

**Comment by vinifarias** [comment]
@jessescn  can I take ` triaging-github-issues` ?

**Comment by jessescn** [comment]
@vinifarias of course! feel free to send any questions in our discord and remember to read the contributing before start translating!

**Comment by jessescn** [comment]
Galera como todos os arquivos já foram alocados, vamos focar em revisar e aceitar os que já foram designados. Caso passe 2 semanas e a pessoa não deu sinal de vida, iremos liberar para outras pessoas poderem traduzir. Futuramente iremos abrir novas issues para tradução, uma vez que ainda temos bastante arquivos pendentes :smile:

**Comment by jessescn** [comment]
@Dennissiq entra no discord que quero falar contigo

**Comment by Dennissiq** [comment]
Te chamei lá @jessescn :)

**Comment by tamirisapbonicenha** [comment]
If you release more translations, give me some ;)

**Comment by Dennissiq** [comment]
@tamirisapbonicenha em breve vamos liberar mais traduções! Conforme formos liberandos as PRs, poderá contruibuir e fazer o Gatsby melhor :) 

Sinta-se a vontade para entrar em nosso [**discord**](https://discordapp.com/invite/xJWpW9U) e participar de nossas discussões! 💜

**Comment by lcnogueira** [comment]
Assim como a @tamirisapbonicenha , também quero contribuir, @Dennissiq . Se possível, por favor, avisa lá no discord quando liberar mais traduções 🙏 .

**Comment by Italox** [comment]
@tamirisapbonicenha @lcnogueira Estamos com novos arquivos disponiveis em #57 , deem uma olhada.

**Comment by rafaeelaudibert** [comment]
Olá @cassule e @willian-viana ! Alguma novidade para conseguir fazer a tradução dos arquivos assigned pra vocês?

Se vocês estiverem sem tempo acho que seria legal liberar esses dois arquivos pra outras pessoas traduzirem, já que eles são extremamente importantes pro projeto. O que vocês me dizem?

**Comment by thiagorowof** [comment]
> Olá @cassule e @willian-viana ! Alguma novidade para conseguir fazer a tradução dos arquivos assigned pra vocês?
> 
> Se vocês estiverem sem tempo acho que seria legal liberar esses dois arquivos pra outras pessoas traduzirem, já que eles são extremamente importantes pro projeto. O que vocês me dizem?

Estou aqui ansioso pra contribuir mais, só esperando alguém liberar algo kkkkk :P

**Comment by lcnogueira** [comment]
@thiagorowof, já viu a issue #57? Tem bastante lá 🙂

**Comment by rafaeelaudibert** [comment]
Como faz um tempinho que não temos resposta, acabei de liberar as issues solicitadas por @cassule e @willian-viana para outras pessoas poderem pegar!

Só pedir aqui, que a gente assigna pra vocês aí!

**Comment by vsmjr** [comment]
Posso pegar a _community-contributions_?

**Comment by abnersajr** [comment]
@vsmjr pode sim.

**Comment by vsmjr** [comment]
É possível assumir _where-to-participate_ enquanto _community-contributions_, que também está comigo, está sob revisão? Bora acabar essa parte hahaha

**Comment by jessescn** [comment]
Precisa ter pressa não @vsmjr. Provavelmente seu PR vai ser aceito logo e quando acabar eu repasso pra ti. É só pra manter os processos de contribuição mesmo :smile:

**Comment by jpedroschmitz** [comment]
Posso pegar `where-to-participate`!

**Comment by jessescn** [comment]
@jpedroschmitz tu poderia pegar alguma da batch #3 (lá tem bastante trabalho)? eu tinha dito a @vsmjr que ele podia pegar essa quando o PR da outra fosse aceita

**Comment by jpedroschmitz** [comment]
Como faltava só um arquivo nessa issue, eu pensei em pegar esse arquivo, para finalizar ela 😀
Mas vou escolher um arquivo na issue 3 então 💜

**Comment by vsmjr** [comment]
@jessescn Tô livre pra pegar ``where-to-participate``, a #142 já foi aceita

**Comment by rafaeelaudibert** [comment]
Toda sua, @vsmjr!

**Comment by jessescn** [comment]
Arquivo `how-to-pitch-gatsby` liberado para poder ser traduzido!

**Comment by peaonunes** [comment]
Posso traduzir `how-to-pitch-gatsby` 😄

**Comment by abnersajr** [comment]
@peaonunes yes you can. You can take some insights from this closed PR.

**Comment by iaurg** [comment]
Estou fechando esta issue, o último arquivo #209 foi traduzido, aprovado e incluso no projeto.
